"""Minimal Phase 1 models for the attack -> target -> judge loop."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


VULNERABILITY_CATEGORIES = (
    "jailbreak",
    "roleplay",
    "authority",
    "hypothetical",
    "escalation",
    "pii_extraction",
    "competitor_bypass",
    "prompt_override",
)


VulnerabilityCategory = Literal[
    "jailbreak",
    "roleplay",
    "authority",
    "hypothetical",
    "escalation",
    "pii_extraction",
    "competitor_bypass",
    "prompt_override",
]

Verdict = Literal["safe", "violation", "inconclusive", "error"]
Severity = Literal["low", "medium", "high", "critical"]


class Attack(BaseModel):
    """An adversarial prompt generated by RedShield."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    title: str = ""
    prompt: str = Field(..., min_length=1)
    intent: str = Field(..., min_length=1)
    expected_failure_mode: str | None = None
    round_index: int = Field(default=1, ge=1)


class TargetResponse(BaseModel):
    """The target application's response to one attack."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    response_text: str = ""
    latency_ms: int | None = Field(default=None, ge=0)
    model: str | None = None
    error: str | None = None

    @model_validator(mode="after")
    def require_response_or_error(self) -> TargetResponse:
        """Ensure the adapter returns target text or a sanitized error."""

        if not self.response_text and not self.error:
            raise ValueError("TargetResponse requires response_text or error.")
        return self


class JudgeResult(BaseModel):
    """The safety judgment for one attack and target response."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    verdict: Verdict
    severity: Severity | None = None
    violated_rule: str | None = None
    reason: str = Field(..., min_length=1)
    evidence: str | None = None
    confidence: float = Field(..., ge=0.0, le=1.0)

    @model_validator(mode="after")
    def require_severity_only_for_violations(self) -> JudgeResult:
        """Keep severity meaningful instead of forcing fake safe severities."""

        if self.verdict == "violation" and self.severity is None:
            raise ValueError("Violation verdicts require severity.")
        if self.verdict != "violation" and self.severity is not None:
            raise ValueError("Only violation verdicts may include severity.")
        return self


class SafetySummary(BaseModel):
    """Terminal summary for a safety scan."""

    model_config = ConfigDict(extra="forbid")

    total_attacks: int = Field(..., ge=0)
    completed_attacks: int = Field(..., ge=0)
    violations: int = Field(..., ge=0)
    safe: int = Field(..., ge=0)
    inconclusive: int = Field(..., ge=0)
    errors: int = Field(..., ge=0)
    violation_rate: float = Field(..., ge=0.0, le=1.0)
    initial_violation_rate: float | None = Field(default=None, ge=0.0, le=1.0)
    final_violation_rate: float | None = Field(default=None, ge=0.0, le=1.0)
    findings: list["VulnerabilityFinding"] = Field(default_factory=list)
    patches_applied: list["PromptPatch"] = Field(default_factory=list)
    remaining_risks: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_counts(self) -> SafetySummary:
        """Ensure summary counts describe one coherent terminal run."""

        if self.completed_attacks > self.total_attacks:
            raise ValueError("completed_attacks cannot exceed total_attacks.")

        counted_results = self.violations + self.safe + self.inconclusive + self.errors
        if counted_results != self.completed_attacks:
            raise ValueError(
                "violations + safe + inconclusive + errors must equal "
                "completed_attacks."
            )

        expected_rate = (
            self.violations / self.completed_attacks
            if self.completed_attacks
            else 0.0
        )
        if abs(self.violation_rate - expected_rate) > 0.000001:
            raise ValueError("violation_rate must equal violations/completed_attacks.")

        return self


class VulnerabilityFinding(BaseModel):
    """Deterministic finding for one vulnerability category."""

    model_config = ConfigDict(extra="forbid")

    finding_id: str = ""
    category: VulnerabilityCategory
    name: str = ""
    description: str = ""
    affected_attack_ids: list[str] = Field(default_factory=list)
    root_cause: str = ""
    severity: Severity | None = None
    recommendation: str = ""
    total: int = Field(..., ge=0)
    violations: int = Field(..., ge=0)
    safe: int = Field(..., ge=0)
    inconclusive: int = Field(..., ge=0)
    errors: int = Field(..., ge=0)
    violation_rate: float = Field(..., ge=0.0, le=1.0)
    dominant: bool = False
    representative_examples: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_finding_counts(self) -> VulnerabilityFinding:
        """Ensure category-level counts are internally consistent."""

        counted_results = self.violations + self.safe + self.inconclusive + self.errors
        if counted_results != self.total:
            raise ValueError(
                "violations + safe + inconclusive + errors must equal total."
            )

        expected_rate = self.violations / self.total if self.total else 0.0
        if abs(self.violation_rate - expected_rate) > 0.000001:
            raise ValueError("violation_rate must equal violations/total.")

        return self


class PromptPatch(BaseModel):
    """Structured prompt patch proposal for one vulnerability category."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    patch_id: str = Field(..., min_length=1)
    round_index: int = Field(default=1, ge=1)
    category: VulnerabilityCategory
    target_finding_ids: list[str] = Field(default_factory=list)
    target_vulnerability: str = Field(..., min_length=1)
    patch_text: str = Field(..., min_length=1)
    rationale: str = Field(..., min_length=1)
    expected_tradeoffs: list[str] = Field(default_factory=list)
    source_violation_rate: float = Field(..., ge=0.0, le=1.0)


class VerificationResult(BaseModel):
    """Result of re-testing previously successful attacks against one patch."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    patch_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    retested_attack_ids: list[str]
    passed_attack_ids: list[str] = Field(default_factory=list)
    failed_attack_ids: list[str] = Field(default_factory=list)
    mitigated_attack_ids: list[str]
    remaining_attack_ids: list[str]
    error_attack_ids: list[str]
    errors: int = Field(..., ge=0)
    before_violation_rate: float = Field(..., ge=0.0, le=1.0)
    after_violation_rate: float = Field(..., ge=0.0, le=1.0)
    improvement: float = Field(..., ge=-1.0, le=1.0)
    violation_rate_reduction: float = Field(default=0.0, ge=-1.0, le=1.0)
    vulnerabilities_mitigated: list[VulnerabilityCategory] = Field(
        default_factory=list
    )
    vulnerabilities_remaining: list[VulnerabilityCategory] = Field(
        default_factory=list
    )
    evidence: list["VerificationEvidence"] = Field(default_factory=list)
    metrics: "VerificationMetrics | None" = None
    mitigated: bool

    @model_validator(mode="after")
    def validate_verification_counts(self) -> VerificationResult:
        """Ensure verification attack IDs describe one coherent retest."""

        if self.errors != len(self.error_attack_ids):
            raise ValueError("errors must equal len(error_attack_ids).")

        resolved_count = len(self.mitigated_attack_ids) + len(
            self.remaining_attack_ids
        ) + len(self.error_attack_ids)
        if resolved_count != len(self.retested_attack_ids):
            raise ValueError(
                "mitigated_attack_ids + remaining_attack_ids + errors must "
                "match retested_attack_ids."
            )

        expected_before = 1.0 if self.retested_attack_ids else 0.0
        if abs(self.before_violation_rate - expected_before) > 0.000001:
            raise ValueError(
                "before_violation_rate must be 1.0 when attacks are retested "
                "and 0.0 when none are retested."
            )

        unresolved_count = len(self.remaining_attack_ids) + len(self.error_attack_ids)
        expected_after = (
            unresolved_count / len(self.retested_attack_ids)
            if self.retested_attack_ids
            else 0.0
        )
        if abs(self.after_violation_rate - expected_after) > 0.000001:
            raise ValueError(
                "after_violation_rate must equal remaining or errored retests "
                "divided by total retests."
            )

        expected_improvement = self.before_violation_rate - self.after_violation_rate
        if abs(self.improvement - expected_improvement) > 0.000001:
            raise ValueError("improvement must equal before_violation_rate minus after.")

        if abs(self.violation_rate_reduction - expected_improvement) > 0.000001:
            raise ValueError(
                "violation_rate_reduction must equal before_violation_rate minus after."
            )

        if self.metrics is not None:
            if self.metrics.total_retested != len(self.retested_attack_ids):
                raise ValueError("metrics.total_retested must match retested attacks.")
            if self.metrics.error_count != self.errors:
                raise ValueError("metrics.error_count must match errors.")
            if abs(self.metrics.violation_rate_reduction - expected_improvement) > 0.000001:
                raise ValueError(
                    "metrics.violation_rate_reduction must match improvement."
                )

        return self


class VerificationEvidence(BaseModel):
    """Evidence comparing a known baseline violation to patched behavior."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    baseline_verdict: Verdict = "violation"
    patched_verdict: Verdict
    mitigated: bool
    reason: str = Field(..., min_length=1)
    patched_response_excerpt: str | None = None


class VerificationMetrics(BaseModel):
    """Structured metrics for one patch verification result."""

    model_config = ConfigDict(extra="forbid")

    total_retested: int = Field(..., ge=0)
    baseline_violations: int = Field(..., ge=0)
    patched_violations: int = Field(..., ge=0)
    mitigated_count: int = Field(..., ge=0)
    remaining_count: int = Field(..., ge=0)
    error_count: int = Field(..., ge=0)
    before_violation_rate: float = Field(..., ge=0.0, le=1.0)
    after_violation_rate: float = Field(..., ge=0.0, le=1.0)
    violation_rate_reduction: float = Field(..., ge=-1.0, le=1.0)
    vulnerabilities_mitigated: list[VulnerabilityCategory] = Field(
        default_factory=list
    )
    vulnerabilities_remaining: list[VulnerabilityCategory] = Field(
        default_factory=list
    )

    @model_validator(mode="after")
    def validate_metrics(self) -> VerificationMetrics:
        """Ensure verification metrics describe the retest bucket counts."""

        if self.baseline_violations != self.total_retested:
            raise ValueError("baseline_violations must equal total_retested.")

        resolved_count = (
            self.mitigated_count + self.remaining_count + self.error_count
        )
        if resolved_count != self.total_retested:
            raise ValueError(
                "mitigated_count + remaining_count + error_count must equal "
                "total_retested."
            )

        expected_before = 1.0 if self.total_retested else 0.0
        if abs(self.before_violation_rate - expected_before) > 0.000001:
            raise ValueError(
                "before_violation_rate must be 1.0 when attacks are retested "
                "and 0.0 when none are retested."
            )

        if self.patched_violations != self.remaining_count + self.error_count:
            raise ValueError(
                "patched_violations must equal remaining_count + error_count."
            )

        expected_after = (
            self.patched_violations / self.total_retested
            if self.total_retested
            else 0.0
        )
        if abs(self.after_violation_rate - expected_after) > 0.000001:
            raise ValueError(
                "after_violation_rate must equal patched_violations/total_retested."
            )

        expected_reduction = self.before_violation_rate - self.after_violation_rate
        if abs(self.violation_rate_reduction - expected_reduction) > 0.000001:
            raise ValueError(
                "violation_rate_reduction must equal before_violation_rate minus after."
            )

        return self
