"""Minimal Phase 1 models for the attack -> target -> judge loop."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


VULNERABILITY_CATEGORIES = (
    "jailbreak",
    "roleplay",
    "authority",
    "hypothetical",
    "escalation",
    "pii_extraction",
    "competitor_bypass",
    "prompt_override",
)


VulnerabilityCategory = Literal[
    "jailbreak",
    "roleplay",
    "authority",
    "hypothetical",
    "escalation",
    "pii_extraction",
    "competitor_bypass",
    "prompt_override",
]

Verdict = Literal["safe", "violation", "inconclusive", "error"]
Severity = Literal["low", "medium", "high", "critical"]


class Attack(BaseModel):
    """An adversarial prompt generated by RedShield."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    prompt: str = Field(..., min_length=1)
    intent: str = Field(..., min_length=1)


class TargetResponse(BaseModel):
    """The target application's response to one attack."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    response_text: str = ""
    error: str | None = None

    @model_validator(mode="after")
    def require_response_or_error(self) -> TargetResponse:
        """Ensure the adapter returns target text or a sanitized error."""

        if not self.response_text and not self.error:
            raise ValueError("TargetResponse requires response_text or error.")
        return self


class JudgeResult(BaseModel):
    """The safety judgment for one attack and target response."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    attack_id: str = Field(..., min_length=1)
    category: VulnerabilityCategory
    verdict: Verdict
    severity: Severity | None = None
    reason: str = Field(..., min_length=1)
    confidence: float = Field(..., ge=0.0, le=1.0)

    @model_validator(mode="after")
    def require_severity_only_for_violations(self) -> JudgeResult:
        """Keep severity meaningful instead of forcing fake safe severities."""

        if self.verdict == "violation" and self.severity is None:
            raise ValueError("Violation verdicts require severity.")
        if self.verdict != "violation" and self.severity is not None:
            raise ValueError("Only violation verdicts may include severity.")
        return self


class SafetySummary(BaseModel):
    """Terminal summary for a Phase 1 safety scan."""

    model_config = ConfigDict(extra="forbid")

    total_attacks: int = Field(..., ge=0)
    completed_attacks: int = Field(..., ge=0)
    violations: int = Field(..., ge=0)
    safe: int = Field(..., ge=0)
    inconclusive: int = Field(..., ge=0)
    errors: int = Field(..., ge=0)
    violation_rate: float = Field(..., ge=0.0, le=1.0)

    @model_validator(mode="after")
    def validate_counts(self) -> SafetySummary:
        """Ensure summary counts describe one coherent terminal run."""

        if self.completed_attacks > self.total_attacks:
            raise ValueError("completed_attacks cannot exceed total_attacks.")

        counted_results = self.violations + self.safe + self.inconclusive + self.errors
        if counted_results != self.completed_attacks:
            raise ValueError(
                "violations + safe + inconclusive + errors must equal "
                "completed_attacks."
            )

        expected_rate = (
            self.violations / self.completed_attacks
            if self.completed_attacks
            else 0.0
        )
        if abs(self.violation_rate - expected_rate) > 0.000001:
            raise ValueError("violation_rate must equal violations/completed_attacks.")

        return self
